---
- name: Ensure other mail agents are not installed
  ansible.builtin.package:
    name:
      - msmtp
      - msmtp-mta
      - ssmtp
    state: absent
  become: true
  become_user: root

- name: Ensure nullmailer is installed
  ansible.builtin.package:
    name:
      - nullmailer
      - mailutils
  become: true
  become_user: root

- name: Deploy defaultdomain configuration
  ansible.builtin.template:
    src: defaultdomain.jinja2
    dest: /etc/nullmailer/defaultdomain
    owner: root
    group: root
    mode: "0644"
  notify: Restart nullmailer
  become: true
  become_user: root

- name: Deploy allmailfrom configuration
  ansible.builtin.template:
    src: allmailfrom.jinja2
    dest: /etc/nullmailer/allmailfrom
    owner: root
    group: root
    mode: "0644"
  notify: Restart nullmailer
  when: nullmailer_allmail_from | length > 0
  become: true
  become_user: root

- name: Remove allmailfrom configuration
  ansible.builtin.file:
    path: /etc/nullmailer/allmailfrom
    state: absent
  notify: Restart nullmailer
  when: nullmailer_allmail_from | length == 0
  become: true
  become_user: root

- name: Deploy adminaddr configuration
  ansible.builtin.template:
    src: adminaddr.jinja2
    dest: /etc/nullmailer/adminaddr
    owner: root
    group: root
    mode: "0644"
  notify: Restart nullmailer
  become: true
  become_user: root

- name: Deploy remotes configuration
  ansible.builtin.template:
    src: remotes.jinja2
    dest: /etc/nullmailer/remotes
    owner: mail
    group: mail
    mode: "0640"
  notify: Restart nullmailer
  become: true
  become_user: root

- name: Configure mailname
  ansible.builtin.template:
    src: mailname.jinja2
    dest: /etc/mailname
    owner: root
    group: root
    mode: "0644"
  notify: Restart nullmailer
  become: true
  become_user: root
